### ISSUE TITLE
[UI] QBackingStore::endPaint() called with active painter on backingstore paint device

### ISSUE THREAD

**Issue by zhang-ray** [zhang-ray/easy-voice-call#10]
OS:  Windows 10
version: https://github.com/zhang-ray/easy-voice-call/commit/a43b283d29147c31c502099c668762e60993a1d4

![image](https://user-images.githubusercontent.com/41682958/47253929-1d309300-d48d-11e8-8c17-635432f88a53.png)

**Comment by zhang-ray** [comment]
https://github.com/zhang-ray/easy-voice-call/commit/08dddef861bda0b0bd8667c825d1a6bf22ff009a fix it?

**Comment by zhang-ray** [comment]
https://github.com/zhang-ray/easy-voice-call/commit/08dddef861bda0b0bd8667c825d1a6bf22ff009a (v0.7.0) use QEvent to postMessage from background thread to UI thread.

resolved!

**Comment by Enn29** [comment]
hello， how to do that which use QEvent to postMessage from background thread to UI thread?
I look forward to your reply

**Comment by zhang-ray** [comment]
> 
> 
> hello， how to do that which use QEvent to postMessage from background thread to UI thread?
> I look forward to your reply

@Enn29 you can see around here: https://github.com/zhang-ray/easy-voice-call/commit/08dddef861bda0b0bd8667c825d1a6bf22ff009a#diff-853aa11baea0c0f534f15f440fcc250bce9a0b13c5bcf453d2892bbd09f8f1d3
